[build-system]
requires = ["setuptools>=58"]
build-backend = "setuptools.build_meta"

[project]
name = "LLMAIx"
version = "0.3.39"
description = "LLM-AIx - A pipeline for information extraction and anonymization of medical documents"
readme = "README.md"
authors = [
    {name = "KatherLab", email = "jakob-nikolas.kather@alumni.dkfz.de"},
]
license = {text = "AGPL-3.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: AGPL-3.0 License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Flask~=3.1.0",
    "Flask-SocketIO~=5.5.1",
    "Flask-WTF~=1.2.2",
    "Flask-SQLAlchemy~=3.1.1",
    "dkpro-cassis~=0.10.1",
    "docx2pdf~=0.1.8",
    "matplotlib~=3.10.1",
    "numpy~=2.2.5",
    "pandas~=2.2.3",
    "pillow~=10.4.0",
    "PyYAML~=6.0.2",
    "seaborn~=0.13.2",
    "requests~=2.32.3",
    "thefuzz~=0.22.1",
    "torch~=2.7.0",
    "torchvision~=0.22.0",
    "transformers~=4.51.3",
    "WTForms~=3.2.1",
    "Flask-HTTPAuth~=4.8.0",
    "python-docx~=1.1.2",
    "timm~=1.0.15",
    "surya-ocr~=0.13.1",
    "scikit-learn~=1.6.1",
    "prometheus_client~=0.21.1",
    "PyMuPDF~=1.25.3",
    "aiohttp~=3.11.18",
    "openpyxl~=3.1.5",
    "openai~=1.76.2"
]

[project.urls]
"Homepage" = "https://github.com/KatherLab/LLMAIx"

[tool.setuptools]
packages = ["LLMAIx"]

[tool.setuptools.cmdclass]
test = "setuptools.command.test.test"

[tool.setuptools.test]
test_suite = "tests"

[project.optional-dependencies]
test = ["unittest"]